# Generated by Django 5.0.6 on 2024-07-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_open_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(to='api.category')),
                ('subcategory', models.ManyToManyField(to='api.subcategory')),
            ],
        ),
    ]
