# Generated by Django 5.0.6 on 2024-07-17 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_is_open_access_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discipline'),
        ),
    ]
